CREATE TABLE [dbo].[Student] (
    [StudentID]   CHAR (8)       NOT NULL,
    [FNameA]      NVARCHAR (MAX) NOT NULL,
    [MNameA]      NVARCHAR (MAX) NOT NULL,
    [LNameA]      NVARCHAR (MAX) NOT NULL,
    [BirthD]      NCHAR (10)     NOT NULL,
    [FNameE]      NVARCHAR (MAX) NOT NULL,
    [MNameE]      NVARCHAR (MAX) NOT NULL,
    [LNameE]      NVARCHAR (MAX) NOT NULL,
    [NaID]        CHAR (16)      NOT NULL,
    [Certificate] CHAR (10)      NOT NULL,
    [Gender]      NCHAR (1)      NOT NULL,
    [Degree]      FLOAT (53)     NOT NULL,
    [Mobile1]     CHAR (11)      NOT NULL,
    [Phone]       CHAR (12)      NULL,
    [Faculty]     CHAR (10)      NOT NULL,
    [Email]       NVARCHAR (MAX) NOT NULL,
    [Password]    NVARCHAR (MAX) NOT NULL,
    PRIMARY KEY CLUSTERED ([StudentID] ASC),
    CONSTRAINT [CK_Student_Column] CHECK ([Gender]='M' OR [Gender]='F')
);